trigger:
- master

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  BuildConfiguration: 'Release'
  isCD: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

stages:
- stage: Build
  displayName: Build
  pool: Azure
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - task: DotNetCoreCLI@1
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        workingDir: src/Web/WebDrapo
        verbose: false
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'
      enabled: false
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: false
    - task: NuGetCommand@2
      displayName: 'NuGet pack'
      condition: eq(variables['isCD'], 'true')
      inputs:
        command: 'pack'
        packagesToPack: '**\*.nuspec'
        versioningScheme: byBuildNumber
    - task: NuGetCommand@2
      displayName: 'NuGet push nuget'
      condition: eq(variables['isCD'], 'true')
      inputs:
        command: push
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        nuGetFeedType: external
        publishFeedCredentials: nuget
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()
    - task: DotNetCoreCLI@1
      displayName: 'Publish Docker'
      condition: eq(variables['isCD'], 'true')
      inputs:
        command: publish
        arguments: '--configuration $(BuildConfiguration) --output published'
        zipAfterPublish: false
    - task: PowerShell@2
      displayName: 'remove drapo/demo image'
      condition: eq(variables['isCD'], 'true')
      inputs:
        targetType: 'inline'
        script: 'docker rmi drapo/demo --force'
      continueOnError: true
    - task: Docker@2
      displayName: 'docker build drapo/demo image'
      condition: eq(variables['isCD'], 'true')
      inputs:
        containerRegistry: 'docker'
        repository: 'drapo/demo'
        command: 'build'
        dockerFile: '**/published/**/*Dockerfile'
        tags: latest
    - task: PowerShell@2
      displayName: 'docker push drapo/demo'
      condition: eq(variables['isCD'], 'true')
      inputs:
        targetType: 'inline'
        script: 'docker push drapo/demo'